Repository Vision-Challengethon-TEAM-1/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#4 Fix: docker-compose.yml 원복
  .github/PULL_REQUEST_TEMPLATE.md
  deploy.sh
  docker-compose.yml
Labels: 🛠️ Fix, 🌏 Infra

#8 Feat: 예외 처리 및 예외 핸들러 작성
  src/main/java/com/vision_hackathon/cheollian/util/README.md
  src/main/java/com/vision_hackathon/cheollian/util/exception/BaseExceptionHandler.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/ExceptionHandlerOrder.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/handler/BusinessExceptionHandler.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/handler/ExternalExceptionHandler.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/handler/SecurityExceptionHandler.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/business/ApplicationLogicException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/business/BadRequestException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/business/DuplicatedException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/business/NotFoundException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/global/GlobalException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/security/AuthenticationFailedException.java
  src/main/java/com/vision_hackathon/cheollian/util/exception/support/security/SecurityException.java
Labels: ✨ Feature

#11 Infra: CI/CD workflow 구축
  .github/workflows/develop-cd.yml
  .github/workflows/develop-ci.yml
  build.gradle
  src/test/java/com/vision_hackathon/cheollian/CheollianApplicationTests.java
Labels: 🌏 Infra
